# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(default=0, related_name='_user_friends_+', to='login_app.User'),
        ),
    ]
